# Generated migration for ReviewConfiguration watch_push_branches field

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('path_with_namespace', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=500)),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '私有'), ('internal', '内部')], default='private', max_length=20)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, db_index=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('mr_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'gitlab_projects',
                'ordering': ['name'],
                'indexes': [
                    models.Index(fields=['path_with_namespace'], name='core_gitla_path__with_n_idx'),
                    models.Index(fields=['is_active', 'last_sync_at'], name='core_gitla_is_acti_last_s_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ReviewConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_review_on_open', models.BooleanField(default=False, verbose_name='MR 打开时自动审查')),
                ('auto_review_commands', models.JSONField(blank=True, default=list, verbose_name='自动审查命令')),
                ('auto_review_on_push', models.BooleanField(default=False, verbose_name='推送时自动审查')),
                ('auto_review_push_commands', models.JSONField(blank=True, default=list, verbose_name='推送审查命令')),
                ('watch_push_branches', models.JSONField(
                    blank=True,
                    default=list,
                    verbose_name='监听 Push 的分支',
                    help_text='空列表表示监听所有分支，否则只监听列表中的分支'
                )),
                ('ignore_draft', models.BooleanField(default=True, verbose_name='忽略草稿 MR')),
                ('ignore_title_patterns', models.JSONField(blank=True, default=list, verbose_name='忽略标题模式')),
                ('ignore_branch_patterns', models.JSONField(blank=True, default=list, verbose_name='忽略分支模式')),
                ('ignore_label_patterns', models.JSONField(blank=True, default=list, verbose_name='忽略标签模式')),
                ('ignore_file_patterns', models.JSONField(blank=True, default=list, verbose_name='忽略文件模式')),
                ('review_extra_instructions', models.TextField(blank=True, verbose_name='额外审查指令')),
                ('review_max_findings', models.PositiveIntegerField(default=3, verbose_name='最大发现问题数')),
                ('review_require_tests', models.BooleanField(default=True, verbose_name='要求测试审查')),
                ('review_require_security', models.BooleanField(default=True, verbose_name='要求安全审查')),
                ('review_require_estimate_effort', models.BooleanField(default=True, verbose_name='要求估算工作量')),
                ('ai_model', models.CharField(default='gpt-4o', max_length=100, verbose_name='AI 模型')),
                ('ai_temperature', models.FloatField(default=0.2, verbose_name='AI 温度参数')),
                ('ai_max_tokens', models.PositiveIntegerField(default=16000, verbose_name='最大 Token 数')),
                ('publish_output', models.BooleanField(default=True, verbose_name='发布输出')),
                ('publish_inline_comments', models.BooleanField(default=True, verbose_name='发布行内评论')),
                ('use_persistent_comment', models.BooleanField(default=True, verbose_name='使用持久化评论')),
                ('verbosity_level', models.IntegerField(default=0, verbose_name='详细程度')),
                ('enable_auto_approval', models.BooleanField(default=False, verbose_name='启用自动审批')),
                ('auto_approve_threshold', models.IntegerField(default=9, verbose_name='自动审批阈值')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.gitlabproject')),
            ],
            options={
                'db_table': 'review_configurations',
                'verbose_name': '审查配置',
                'verbose_name_plural': '审查配置',
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mr_id', models.PositiveIntegerField(db_index=True)),
                ('mr_iid', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('source_branch', models.CharField(max_length=255)),
                ('target_branch', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('opened', '开启'), ('closed', '关闭'), ('merged', '已合并'), ('locked', '锁定')], db_index=True, default='opened', max_length=20)),
                ('draft', models.BooleanField(db_index=True, default=False)),
                ('url', models.URLField(max_length=500)),
                ('gitlab_created_at', models.DateTimeField()),
                ('gitlab_updated_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('changed_files', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mrs', to='core.gitlabuser')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_mrs', to='core.gitlabuser')),
                ('project', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.gitlabproject')),
            ],
            options={
                'db_table': 'pull_requests',
                'ordering': ['-gitlab_created_at'],
                'indexes': [
                    models.Index(fields=['project', 'state'], name='core_pull_r_project_id_state_idx'),
                    models.Index(fields=['project', 'draft', 'state'], name='core_pull_r_project_id_draft_idx'),
                    models.Index(fields=['-gitlab_created_at'], name='core_pull_r_gitlab_c_idx'),
                ],
                'unique_together': {('project', 'mr_iid')},
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('review_type', models.CharField(choices=[('review', '代码审查'), ('describe', '描述生成'), ('improve', '代码改进'), ('question', '问答'), ('update_changelog', '更新日志'), ('generate_labels', '生成标签')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('queued', '队列中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20)),
                ('triggered_by', models.CharField(max_length=50)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_temperature', models.FloatField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='core.pullrequest')),
                ('trigger_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_tasks', to='core.gitlabuser')),
            ],
            options={
                'db_table': 'review_tasks',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['pull_request', '-created_at'], name='core_review_pull_reques_idx'),
                    models.Index(fields=['status', '-created_at'], name='core_review_status__idx'),
                    models.Index(fields=['review_type', '-created_at'], name='core_review_review_type_idx'),
                    models.Index(fields=['task_id'], name='core_review_task_id_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='GitLabUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gitlab_user_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('gitlab_username', models.CharField(db_index=True, max_length=255)),
                ('gitlab_email', models.EmailField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_profile', to='auth.user')),
            ],
            options={
                'db_table': 'gitlab_users',
                'ordering': ['gitlab_username'],
                'indexes': [
                    models.Index(fields=['gitlab_user_id'], name='core_gitlab__gitlab_use_idx'),
                    models.Index(fields=['gitlab_username'], name='core_gitlab__gitlab_us_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('review_start', '开始审查'), ('review_complete', '完成审查'), ('config_change', '配置变更'), ('webhook_event', 'Webhook 事件')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.gitlabproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.gitlabuser')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='core_audit__user_id_idx'),
                    models.Index(fields=['project', '-created_at'], name='core_audit__project_i_idx'),
                    models.Index(fields=['action', '-created_at'], name='core_audit__action___idx'),
                    models.Index(fields=['resource_type', 'resource_id'], name='core_audit__resource___idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('discussion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_type', models.CharField(choices=[('overall', '整体评论'), ('file', '文件评论'), ('line', '行内评论')], default='overall', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('line_start', models.PositiveIntegerField(blank=True, null=True)),
                ('line_end', models.PositiveIntegerField(blank=True, null=True)),
                ('side', models.CharField(blank=True, max_length=10, null=True)),
                ('is_persistent', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.reviewtask')),
            ],
            options={
                'db_table': 'review_comments',
                'ordering': ['id'],
                'indexes': [
                    models.Index(fields=['task', 'comment_type'], name='core_review_task_id__idx'),
                    models.Index(fields=['file_path'], name='core_review__file_path_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('review', '代码审查'), ('describe', '描述生成'), ('improve', '代码改进'), ('question', '问答'), ('update_changelog', '更新日志'), ('generate_labels', '生成标签')], max_length=20)),
                ('overall_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('effort_estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('critical_issues', models.PositiveIntegerField(default=0)),
                ('major_issues', models.PositiveIntegerField(default=0)),
                ('minor_issues', models.PositiveIntegerField(default=0)),
                ('suggestions', models.PositiveIntegerField(default=0)),
                ('report_data', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('pull_request', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.pullrequest')),
            ],
            options={
                'db_table': 'review_reports',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['pull_request', '-created_at'], name='core_review__pull_requ_idx'),
                    models.Index(fields=['review_type', '-created_at'], name='core_review__review_ty_idx'),
                ],
            },
        ),
    ]
